### PR TITLE
Add serverside rendering for /login

### PR DESCRIPTION
**Pull request by 0x53A**

### CODE REVIEW

**Comment by 0x53A** [comment]
SSR was already enabled for ``/``, so I don't think so?

I did ``build runssr``, and it seemed to work ok.

Anything special you want me to check?

Of course the SSR is only active if I directly navigate to ``/login``, if I first navigate to ``/``, then click on login, it is rendered client-side (as it should be).

------

I wanted to make it clear that SSR can - in theory - be used for any page, just the home page is not that much.

**Comment by forki** [comment]
https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Client/App.fs#L58

That's where the hydrate part is kicking in. For login it does not make any difference since that page doesn't do any further web requests. But in general case we want to hydrate the server side calculated model into the runtime js model. 

An example could be a public wishlist. You would render it on serverless side and additionally you would hydrate the array of books into the model. So you would save that additional round trip.

**Comment by forki** [comment]
And ftr SSR with hydrate is awesome! That's all.

**Comment by 0x53A** [comment]
Ah, didn't know that ;D

I added some comments, what do you think?

**Comment by 0x53A** [comment]
Do you have any public examples for a complicated hydrate @forki ?

**Comment by forki** [comment]
Nothing public. Maybe @zaaack has something. And I think we should still hydrate all SSR pages. This will ensure compiler complains if we change model later to something more complicated

**Comment by 0x53A** [comment]
> And I think we should still hydrate all SSR pages. This will ensure compiler complains if we change model later to something more complicated

Like this?

```fsharp
let hydrateModel (json:string) : Model * Cmd<_> =
    // The page was rendered server-side and now react client-side kicks in.
    // If needed, the model could be fixed up here.
    // In this case we just deserialize the model from the json and don't need to to anything special.
    let model : Model = ofJson json
    match model.PageModel with
    | HomePageModel -> model, Cmd.none
    | LoginModel _ -> model, Cmd.none
| WishListModel _ -> model, Cmd.none
```

**Comment by forki** [comment]
Yep

**Comment by 0x53A** [comment]
ah, I didn't even see the ``Some Page.Home``.

**Comment by forki** [comment]
Uh something is red?

**Comment by 0x53A** [comment]
Net SDK download failure 

https://travis-ci.org/SAFE-Stack/SAFE-BookStore/builds/422204639#L2343

**Comment by forki** [comment]
💯

**Pull request merged**
