### PR TITLE
Freya implementation

### PR DESCRIPTION
**Pull request by nojaf**
Initial attempt to replace Giraffe with Freya. See #199

### CODE REVIEW

**Comment by forki** [comment]
Why do you want to replace giraffe with Freya?

**Comment by nojaf** [comment]
See #199

**Comment by kolektiv** [comment]
This looks good! Thumbs up from me 👍

**Comment by nojaf** [comment]
@alfonsogarciacaro what would it take to merge this PR? Travis failed for no good reason.

**Comment by alfonsogarciacaro** [comment]
Sorry @nojaf, I'm not always watching this repo so didn't see the PR. As this is just an extra branch, I don't see any reason not to merge, so let's do it! If you want you can also send a PR to master's README to add a link to the branch for an alternative to the backend :+1:

**Comment by nojaf** [comment]
Thanks Alfonso, I'll send a PR to the master branch.

**Comment by nojaf** [comment]
See https://github.com/SAFE-Stack/SAFE-BookStore/pull/348

**Pull request merged**
