### PR TITLE
 Build inside the Dockerfile

### PR DESCRIPTION
**Pull request by vbfox**
Also:
* Bump SDK version
* Fixes `/Images/` vs `/images/` on linux

### CODE REVIEW

**Comment by forki** [comment]
This means everyone who tries it needs docker installed?

**Comment by vbfox** [comment]
What it changes or not:

* Normal build still works locally as before
* Docker build (As in `docker build .`) now run the full tests+build in a container and generate a working container. It can work with just docker installed (No .Net framework, no .net Core, no Fsharp)
* The build done in docker is done on linux whatever the host OS is doesn't count
* First docker build is very slow because it download mono and paket and yarn download half the planet
* As the docker builder download things entreprise proxies are pretty much guaranteed to not work (Especially `apt` as it doesn't respect `HTTP_PROXY` and require custom config.
* Full deploy with docker now does the build twice (Once on the host PC and once inside docker)

A few decisions to make:

* Do we provide 2 Dockerfile one doing the build inside and one outside ?
* If the "build in docker" version is the one used in the FAKE build maybe the tasks in questions should not depend on the local build ?

**Comment by vbfox** [comment]
Also the idea for the feature (I mean except from me wanting to play with docker) is issue #234.

**Comment by kfrie** [comment]
For those people who use Docker and are sceptical towards SAFE and F# ecosystem this is a great thing. It allows them to explore BookStore without cluttering their system. Something I always do if I explore an unknown ground :)

**Comment by forki** [comment]
@kfrie we only need to make sure the other way holds as well - people who don't want to docker need to be able to run it.

**Comment by kfrie** [comment]
I assumed it is served as an option :) But to address the open questions of @vbfox : 

* We must ensure that this Docker thing is just additive, so we can't touch existing `build.fsx` targets and current Dockerfile. So maybe by create a subfolder `DockerizedBuild` where you place the new file
* Then create a "Docker-only" variant of every depending target and define a 2nd, Docker-only build chain in "build.fsx". Bypassing tests could be a build parameter
* Update README.md and present the Docker-only option.

**Comment by vbfox** [comment]
* Moved to a separate dockerfile (Not in a directory dockerfiles hate directories)
* Add some info on usage in readme (For both the old and the new dockerfile)

**Comment by kfrie** [comment]
@vbfox  Good to know, theres always something to learn for a Docker convenience user like me 😅

**Comment by vbfox** [comment]
@kfrie Essentially `docker build` is using inception, it's first packaging the dir passed as parameter in a zip, spinning a special container, sending the zip to the container and building the dockerfile here... so the second parameter is crucial.

if you have your dockerfile in a directory it can work by doing `docker build -f dir/Dockerfile .` (from the parent) or `docker build ..` in the child but it's hard to remember, users get tripped by it and you don't gain anything from placing it along the other ones.

**Comment by vbfox** [comment]
@forki is there a way for this PR to move forward or should I close it ?

**Comment by forki** [comment]
soryy for got about it. can you please rebase on master?

**Comment by vbfox** [comment]
Here is a new versions with quite a few changes:

* I changed the normal Dockerfile to use a more recent aspnet image based on alpine (smaller) & also use a pinned version of the aspnet image
* The image is now based on [vbfox/fable-build](https://hub.docker.com/r/vbfox/fable-build/) because it's a configuration I needed elsewhere & there is no need to copy it
* The docker build no longer run the tests. This is because the client ones can't be run as-is. As the driver moved to chrome it would need a X-Windows subsystem and a full install of chrome to run, it's possible in docker but quite involved (See https://hub.docker.com/r/robcherry/docker-chromedriver/~/dockerfile/ ). So I made the `BundleClient` target in FAKE no longer depend on the tests and use that.

(I might do some sort of `-full` version of `vbfox/fable-build` that can run the tests at some point)

**Pull request closed without merging**
