### PR TITLE
Check version before installing dotnet cli

### PR DESCRIPTION
**Pull request by kunjee17**
I have added version check and also printing if something is wrong. Now it will check and install if and only if that is required.

### CODE REVIEW

**Comment by forki** [comment]
That is already part of fake. If it doesn't work for you we need to fix it over there

**Comment by forki** [comment]
That is already part of fake. If it doesn't work for you we need to fix it over there

**Comment by kunjee17** [comment]
@forki it doesn't work for me. It was installing dotnet core again and again for me. I ll have a look at it in over Fake.

**Comment by rommsen** [comment]
@kunjee17 we had the same problem but updating fake to the latest version fixed it

**Comment by kunjee17** [comment]
@rommsen thanks man. I ll update it and have a look.

**Comment by forki** [comment]
actually I forgot to document that we are on 2.1.3 already: https://github.com/SAFE-Stack/SAFE-BookStore/commit/5921d6d46aa8ce297a7297ff33e1f467523d58ef

**Comment by kunjee17** [comment]
@forki @rommsen updating Fake did the trick. thanks man...

**Pull request closed without merging**
