### PR TITLE
Switch to ChromeHeadless

### PR DESCRIPTION
**Pull request by cgravill**

### CODE REVIEW

**Comment by forki** [comment]
https://twitter.com/sforkmann/status/976758077751005184

will be hard right now

**Comment by cgravill** [comment]
Ah, thanks for the warning :-)

**Comment by forki** [comment]
can you please also upgrade it to use canopy 2?

**Comment by cgravill** [comment]
Sure, I've switched Canopy 2 on internal project already so should be able to upgrade this too later.

**Comment by forki** [comment]
Awesome! thanks

**Comment by lefthandedgoat** [comment]
@cgravill I accepted that PR and did a build:  https://www.nuget.org/packages/canopy/2.0.1

**Comment by cgravill** [comment]
@lefthandedgoat thanks! I've updated and added #327

**Pull request merged**
