### PR TITLE
Update to Fable 2.1

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
ok seems it fails for some restore reason @alfonsogarciacaro any ideas?

**Comment by alfonsogarciacaro** [comment]
Fable automatically restores the F# project (this happens since Fable 2, not new in Fable 2.1). It's weird it gives the "Cannot find restore info" error when trying to restore the project 😕 Maybe because it's invoking a "global" dotnet and FAKE uses a local version?

image

**Comment by forki** [comment]
in my production app it fails on ci even weirder:

/usr/bin/yarn webpack-cli --config src/Client/webpack.config.js -p
﻿﻿yarn run v1.12.3
$ /home/gitlab-runner/builds/d5cd2d2a/0/products/eCarApp/node_modules/.bin/webpack-cli --config src/Client/webpack.config.js -p
Bundling for production...
fable-compiler 2.1.0
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Running build failed.

**Comment by alfonsogarciacaro** [comment]
Yes, it seems in the previous build it was just skipping the command and now Appveyor has 2.1.500 so it conflicts with the local install for some reason.

image

Is [this FAKE command](https://github.com/SAFE-Stack/SAFE-BookStore/blob/9ec7bce93882bac6f5cd073280ab99fcb58fad8e/build.fsx#L104) always installing the sdk locally? Cannot use the global "dotnet" if it matches the desired version?

**Comment by alfonsogarciacaro** [comment]
@forki Maybe try to use `webpack` instead of `webpack-cli` in your production app?

**Comment by alfonsogarciacaro** [comment]
I mentioned FAKE and the blame has quickly moved somewhere else ;)

In any case, this is just a convenience, I didn't want the compilation to stop if the restore failed. I'm wrapping the `dotnet restore` [command execution in a try ... with](https://github.com/fable-compiler/Fable/blob/57d7598e70241261b20607f1ac82934796f4c8fa/src/dotnet/Fable.Compiler/CLI/CLI.Util.fs#L185-L195) so I don't know why it stops the compilation. Am I doing something wrong?

**Comment by alfonsogarciacaro** [comment]
AFAIK Dotnet.ProjInfo (which Fable uses to parse the .fsproj file) also uses "dotnet" globally. Is that right @enricosada?

**Comment by forki** [comment]
it's not about blame. We just need to find a way that works on usual CI setups. I mean we knew that moving things back to webpack will introduce new edge cases. so it's just about polishing them out

**Comment by forki** [comment]
ok for testing purposes I do the dotnet restore before calling webpack. but it still fails. I can't really tell if it fails during restore or one step later. 


C:\Program Files (x86)\Yarn\bin\yarn.cmd webpack --config src/Client/webpack.config.js -p
yarn run v1.9.4
$ C:\projects\safe-bookstore\node_modules\.bin\webpack --config src/Client/webpack.config.js -p
Bundling for production...
fable-compiler 2.1.0
CWD: C:\projects\safe-bookstore\src\Client
cmd /C "dotnet" restore Client.fsproj
ERROR: MSBuild failed with exitCode -2147450735 Working Directory: 'C:\projects\safe-bookstore\src\Client' Exe Path: 'dotnet' Args: 'msbuild C:\projects\safe-bookstore\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp7FFA.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp7FFB.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp800B.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=C:\Users\appveyor\AppData\Local\Temp\1\tmp801C.tmp.proj-info.hook.targets /nologo /verbosity:quiet'
   at Fable.CLI.ProjectCoreCracker.projInfo(FSharpList`1 additionalMSBuildProps, String file) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCoreCracker.fs:line 103
   at Fable.CLI.ProjectCracker.fullCrack(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 199
   at Fable.CLI.ProjectCracker.getCrackedProjectsFromMainFsproj(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 274
   at Fable.CLI.ProjectCracker.retry@295(FSharpChecker checker, String projFile, DateTime retryUntil, Unit unitVar0) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 297
   at Fable.CLI.ProjectCracker.getFullProjectOpts(FSharpChecker checker, String[] define, String rootDir, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 359
   at Fable.CLI.Agent.createProject(FSharpChecker checker, String[] dirtyFiles, FSharpOption`1 prevProject, Message msg, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 57
   at Fable.CLI.Agent.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 190
   at Fable.CLI.Agent.loop@260-7.Invoke(Unit unitVar) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 262
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@344-8.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
Hash: 97d09228b17b55a632bd
Version: webpack 4.26.0
Time: 5261ms
Built at: 11/29/2018 2:30:52 PM
 2 assets
Entrypoint main = vendors.js main.js
[110] multi whatwg-fetch @babel/polyfill ./src/Client/Client.fsproj 52 bytes {0} [built]
[113] (webpack)/buildin/global.js 489 bytes {1} [built]
[279] ./src/Client/Client.fsproj 1.18 KiB {0} [built] [failed] [1 error]
    + 277 hidden modules
ERROR in ./src/Client/Client.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: MSBuild failed with exitCode -2147450735 Working Directory: 'C:\projects\safe-bookstore\src\Client' Exe Path: 'dotnet' Args: 'msbuild C:\projects\safe-bookstore\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp7FFA.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp7FFB.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp800B.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=C:\Users\appveyor\AppData\Local\Temp\1\tmp801C.tmp.proj-info.hook.targets /nologo /verbosity:quiet'
    at Loader.getCompiler.send.then.err (C:\projects\safe-bookstore\node_modules\fable-loader\index.js:77:22)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ multi whatwg-fetch @babel/polyfill ./src/Client/Client.fsproj main[2]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Running build failed.
Error:
System.Exception: Error while running 'C:\Program Files (x86)\Yarn\bin\yarn.cmd' with args: webpack --config src/Client/webpack.config.js -p
   at FSI_0005.Build.run@41.Invoke(String message) in C:\projects\safe-bookstore\build.fsx:line 41
   at FSI_0005.Build.run(String cmd, String args, String dir) in C:\projects\safe-bookstore\build.fsx:line 41
   at FSI_0005.Build.clo@128-8.Invoke(Unit _arg6) in C:\projects\safe-bookstore\build.fsx:line 129
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

**Comment by alfonsogarciacaro** [comment]
Looks like the restore wasn't done properly. I've pushed fable-compiler 2.1.1 trying to ignore the error when calling `dotnet restore` (not sure if it will work here). But in any case, if CI is installing a local version of the dotnet SDK, it should add the executable to the environment PATH. There are other places that call `dotnet` globally (DotnetProj.Info, fable-compiler when running the assembly) and I cannot control them all.

**Comment by forki** [comment]
> , it should add the executable to the environment PATH

we can certainly do that. Let me update the fable and then we see

**Comment by forki** [comment]
Alternative Idea: would it be possible to set the dotnet path as command line argument to yarn webpack command? Would that make sense?

@MangelMaxime what do you think?

**Comment by alfonsogarciacaro** [comment]
Well, [you first convince @enricosada](https://github.com/enricosada/dotnet-proj-info/blob/3d8c895dba69cb43ad1ecf9b97ee7cb5d26789f1/src/dotnet-proj/Inspect.fs#L97-L98) and then we talk ;)

**Comment by MangelMaxime** [comment]
TBH I don't understand much about `global.json` so I can't help/advice much. ^^

**Comment by forki** [comment]
Well as very first step I put it in path to see if it's fixing stuff. And
if that's the case then we can iterate on making it even more complicated.
/s/complicated/awesome

Am Do., 29. Nov. 2018, 18:01 hat Alfonso Garcia-Caro <
notifications@github.com> geschrieben:

**Comment by forki** [comment]
The global.json is like a lock file for the .NET sdk. I have a hard time making this clear to everyone ;-)
Folks like @isaacabraham always come and advocate against pinning the sdk ;-)

**Comment by MangelMaxime** [comment]
@forki I do understand that this is a lock files.

But what I find frustrating is that if you have on your system:
- v2.402
- v2.403
- v2.500

Because you installed each version one by one. Then it will never found the earlier version.
Perhaps it is erasing them which is kind of stupid :)

For me it should allow different version and be able to find the one you wants. Because when working with OSS project which have different version in the end I just upgrade all of them to the newest version. Which is fine if I own the repo, but when working with Elmish or Fable repo for example then either I upgrade the `global.json` version and need to remember to not commit that change or I wait 10min that FAKE install the expected version which is just too long and it will do that over and over...

**Comment by MangelMaxime** [comment]
So for libs I should remove it ? 🤔

Sorry to go out of the initial subject ^^

**Comment by forki** [comment]
No please don't. It's still making things more explicit

Am Do., 29. Nov. 2018, 22:16 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
> No please don't. It's still making things more explicit

And making people crazy 😂

But ok, I will not then.

**Comment by forki** [comment]
Yes painfully explicit :P

Am Fr., 30. Nov. 2018, 08:12 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by forki** [comment]
ok that fixes the appveyor. but for some reason the UI tests on travis do not work?
can someone with Linux/Mac try to run locally? something wrong with the app on linux!?

**Comment by forki** [comment]
screenshot_20181130-095329

So it's not the UI tests. It's still the fable call. I don't really understand what's happening here.

@alfonsogarciacaro shouldn't it at least give different exit code?

**Comment by alfonsogarciacaro** [comment]
Yes, Fable should display a better error message. I've build this branch locally on my macOS and it run fine. It's and ENOENT problem (No such directory entry) so Travis is still not finding "dotnet", not sure why... and not sure why it worked before 😕

**Comment by forki** [comment]
It worked before 2.1 because we always started dotnet with full path. Now
webpack process starts it and I'm not sure if the PATH is now good for
Linux. What happens when you deinstall the 2.1.500 globally. Then it should
theoretically install it locally for you and maybe it then crashes as well?

Am Fr., 30. Nov. 2018, 13:06 hat Alfonso Garcia-Caro <
notifications@github.com> geschrieben:

**Comment by alfonsogarciacaro** [comment]
Hmm, but before Fable was also [calling `dotnet restore` globally](https://travis-ci.org/SAFE-Stack/SAFE-BookStore/builds/458760698#L3731) and it worked...

**Comment by forki** [comment]
mhm dunno.

**Comment by alfonsogarciacaro** [comment]
Oh, f*ck. After a lot of trial and error I found the issue, PATH separators are different in Windows and Unix 😡 Please use this:

```fsharp
Target "InstallDotNetCore" (fun _ ->
    dotnetExePath <- DotNetCli.InstallDotNetSDK dotnetcliVersion
    let fi = FileInfo dotnetExePath
    let SEPARATOR = if isWindows then ";" else ":"
    Environment.SetEnvironmentVariable(
        "PATH",
        fi.Directory.FullName + SEPARATOR + System.Environment.GetEnvironmentVariable "PATH",
        EnvironmentVariableTarget.Process)
)
```

It would probably be a good idea to add this as a FAKE helper

**Comment by forki** [comment]
Ouch. Thanks a lot for figuring that out.

/cc @matthid

Am Fr., 30. Nov. 2018, 14:38 hat Alfonso Garcia-Caro <
notifications@github.com> geschrieben:

**Comment by forki** [comment]
Ok it's green. Now let's discuss if we really like that approach. Tbh I'm currently very confused about it. I'm not saying it's bad, but I'm also not really amazed about it. There must be a more elegant solution.

**Comment by forki** [comment]
Ok cool. https://safebookstore.azurewebsites.net is now proper fable 2.1 app and so is my production app. Thanks a lot!

**Pull request merged**
